image: gcc

stages:
  - build
  - test1 # kalman filter
    test2 # extended kalman filter

build:
  stage: build
  before_script:
    - apt-get update --yes
    - apt-get install --yes cmake
    - apt-get install libeigen3-dev
  script:
    - mkdir build
    - cd build
    - cmake .. && make
  artifacts:
    paths:
      - build
  only:
    - master

# run tests using the binary built before
test1:
  stage: kf_test
  script:
    - ./build/kf_test
  only:
    - master

test2:
  stage: ekf_test
  script:
    - ./build/ekf_test
  only:
    - master
