image: gcc

stages:
  - build
  - kf_test   # kalman filter
  - ekf_test  # extended kalman filter

build:
  stage: build
  before_script:
    - apt-get update --yes
    - apt-get install --yes cmake
    - apt-get install libeigen3-dev
  script:
    - mkdir build
    - cd build
    - cmake -DWITH_PLOT_GRAPH=OFF .. && make
  artifacts:
    paths:
      - build
  only:
    - master

# run tests using the binary built before
kf_test:
  stage: kf_test
  script:
    - ./build/kf_test
  only:
    - master

ekf_test:
  stage: ekf_test
  script:
    - ./build/ekf_test
  only:
    - master
